baseURL = ""

title = "Firoz Ansari"

languageCode = "en-GB"

# allow fenced code blocks, instead of `{{< highlight ... >}}` shortcodes,
# which are unwieldly and less fun than using pure Markdown syntax
pygmentsCodeFences = true
# allow us to hook in custom CSS to render the site's styles
pygmentsUseClasses = true

# get information about the Git repo, such as last commit to a file
enableGitInfo = true

ignoreErrors = ["error-remote-getjson"]

paginate = 50

theme = "tale"

[params]
  author = "Firoz Ansari"
  liveSiteUrl = "https://firozansari.com"
  image = "/img/profile.jpg"
  WebMentionDomain = "firozansari.com"
  MaxWebmentions = "100"
  AuthorizationEndpoint = "https://indieauth.firozansari.com/authorize"
  TokenEndpoint = "https://indieauth.firozansari.com/token"
  IndieAuthServer = "https://indieauth.firozansari.com"
  MicroSubEndpoint = "https://aperture.p3k.io/microsub/262"
  MicroPubEndpoint = "https://www-api.firozansari.com/micropub"
  ShowInMainFeed = ["articles", "bookmarks", "listens", "notes", "photos", "reposts", "reads"]
  IgnoreInFeeds = ["", "contacts", "projects", "talks"]
  MaxRssItems = 100
  MaxJsonFeedItems = 100
  CiteTruncateWords = 200
[[params.redirect]]
from = "/tags/archlinux/"
to = "/tags/arch-linux/"
[[params.redirect]]
from = "/tags/capitalone/"
to = "/tags/capital-one/"
[[params.redirect]]
from = "/tags/diversity/"
to = "/tags/diversity-and-inclusion/"
[[params.redirect]]
from = "/tags/inclusivity/"
to = "/tags/diversity-and-inclusion/"
[[params.redirect]]
from = "/.git"
to = "https://gitlab.com/firozansari/jvt.me"
[[params.redirect]]
from = "/mf2/2020/03/nh9y0"
to = "/mf2/2020/03/bl33l/"

[permalinks]
  events = "/:sections/:slug/"
  mf2 = "/mf2/:slug/"
  posts = "/posts/:year/:month/:day/:slug/"
  tags = "/tags/:title/"
  kinds = "/kind/:title/"
  week-notes = "/week-notes/:slug/:filename/"
  music-in-review = "/music-in-review/:filename/"

[taxonomies]
  kind = "kind"
  tag = "tags"
  series = "series"

[outputs]
home = ["HTML", "RSS", "contacts", "jsonFeed", "postFrequency", "redir", "contentDeduplication", "search", "source", "taxonomies"]
section = ["HTML", "eventsCalendar", "RSS"]
page = ["HTML", "eventsCalendar"]

[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
[outputFormats.contacts]
mediatype = "application/json"
baseName = "contacts"
notAlternative = true
[outputFormats.jsonFeed]
mediaType = "application/json"
baseName = "feed"
[outputFormats.postFrequency]
mediaType = "application/json"
baseName = "post-frequency"
[outputFormats.eventsCalendar]
mediaType = "text/calendar"
baseName = "index"
[outputFormats.contentDeduplication]
mediatype = "application/json"
baseName = "content-deduplication"
[outputFormats.redir]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.search]
mediatype = "application/json"
baseName = "search"
notAlternative = true
[outputFormats.source]
mediatype = "application/json"
baseName = "source"
notAlternative = true
[outputFormats.taxonomies]
mediatype = "application/json"
baseName = "taxonomies"
notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
    # disable stupid "smart" quotes
    typographer = false
    [markup.goldmark.renderer]
    # allow inline HTML, such as spoiler warnings
    unsafe = true
  [markup.tableOfContents]
  startLevel = 1
  endLevel = 6
  ordered = false

[menu]
  [[menu.main]]
    identifier = "now"
    name = "/now"
    title = "/now"
    url = "/now/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/kind/articles/"
    weight = 10
  [[menu.main]]
    identifier = "links"
    name = "Links"
    title = "Links"
    url = "/kind/bookmarks/"
    weight = 11
  [[menu.main]]
    identifier = "kind"
    name = "Post by Kind"
    title = "Post by Kind"
    url = "/kind/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    title = "Search"
    url = "/search/"
    weight = 50

  [[menu.footer]]
    identifier = "all"
    name = "All Posts"
    title = "All Posts"
    url = "/all/"
    weight = 10
  [[menu.footer]]
    identifier = "subscribe"
    name = "Follow This Blog"
    title = "Follow This Blog"
    url = "/subscribe/"
    weight = 11
  [[menu.footer]]
    identifier = "talks"
    name = "Talks"
    title = "Talks"
    url = "/talks/"
    weight = 25
  [[menu.footer]]
    identifier = "blogroll"
    name = "Blogroll"
    title = "Blogroll"
    url = "/blogroll/"
    weight = 40
  [[menu.footer]]
    identifier = "popular-posts"
    name = "Popular Posts"
    title = "Popular Posts"
    url = "/popular-posts/"
    weight = 41
  [[menu.footer]]
    identifier = "postvisualisation"
    name = "Post Visualisation"
    title = "Post Visualisation"
    url = "/post-frequency/"
    weight = 45

[deployment]
[[deployment.targets]]
name = "prod"

URL = "s3://www-jvt-me?region=eu-west-2"

[[cascade]]
slug = 2020
[cascade._target]
  path = '/week-notes/2020/**'

[[cascade]]
slug = 2021
[cascade._target]
  path = '/week-notes/2021/**'

[[cascade]]
slug = 2022
[cascade._target]
  path = '/week-notes/2022/**'

[[module.imports]]
# path = "github.com/firozansari/firozansari.theme"